### ISSUE TITLE
How to save fine tuned PaliGemma model?

### ISSUE THREAD

**Issue by SkalskiP** [google-research/big_vision#104]
Hi 👋🏻 

Thanks a lot for PaliGemma fine-tune example [notebook](https://colab.research.google.com/github/google-research/big_vision/blob/main/big_vision/configs/proj/paligemma/finetune_paligemma.ipynb). It worked without any issue. However, it lacks the last step - saving a fine-tuned model. (Or I'm just missing something.) I'd appreciate any help. Thank you. 🙏🏻

**Comment by akolesnikoff** [comment]
Thanks for your question!

I have added an extra colab cell to save the last checkpoint.

**Comment by SkalskiP** [comment]
Awesome, @akolesnikoff 🔥 I really appreciate your help!

**Comment by milaomrani** [comment]
OverflowError: serializing a bytes object larger than 4 GiB requires pickle protocol 4 or higher
