### ISSUE TITLE
Can I convert paligemma npz model to pytorch to safetensors?

### ISSUE THREAD

**Issue by sdip15fa** [google-research/big_vision#107]
Hi, I have tried to fine-tune paligemma using the notebook provided and got .npz models. Is it possible I can convert them to the format as in google/paligemma-3b-pt-224 so I can use them with transformers? Thanks.

**Comment by merveenoyan** [comment]
@sdip15fa hello! I think you can use this script: https://github.com/huggingface/transformers/blob/main/src/transformers/models/paligemma/convert_paligemma_weights_to_hf.py

**Comment by sdip15fa** [comment]
Thanks a lot!

**Comment by AhmedMasryKU** [comment]
@merveenoyan 
I tried the script that you shared, but it's giving me this error. Do you know how to fix it?

`Traceback (most recent call last):
  File "/content/convert_paligemma.py", line 340, in <module>
    convert_paligemma_checkpoint(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/convert_paligemma.py", line 255, in convert_paligemma_checkpoint
    state_dict_transformers = slice_state_dict(state_dict, config)
  File "/content/convert_paligemma.py", line 202, in slice_state_dict
    state_dict[key] = torch.from_numpy(value)
TypeError: can't convert np.ndarray of type numpy.void. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint64, uint32, uint16, uint8, and bool.`
