### ISSUE TITLE
AttributeError pp_img in lit notebook

### ISSUE THREAD

**Issue by amrzv** [google-research/big_vision#18]
Hi.
An AttributeError is raised when running `big_vision/blob/main/big_vision/configs/proj/image_text/lit.ipynb` notebook in colab:
<img width="329" alt="image" src="https://user-images.githubusercontent.com/36787333/188269954-5fa7746e-ad7c-474b-aa47-89d08857da6d.png">

P.S: raised here `config.pp_img`.
P.S.S: here also will be AttributeError: `config.pp_txt`

**Comment by gurkirt** [comment]
I am facing the same issue, I solved the pp_img but pp_txt is still an issue.
I set follow configs in lit_coco.py
```
config.pp_img = f'resize({arg.res})|value_range(-1,1)'
config.pp_txt = 'tokenize(max_len=16, inkey="texts", eos="sticky", pad_value=1)'
```
Image pp works but for pp_txt I get the following error

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/7077539/193451134-e4df1f53-a645-4ff9-93f3-71c28498b32d.png">

Looking forward for your response.

**Comment by bobwan1995** [comment]
Hi, you can instead use 

> config.evals.disclf.pp_img & config.evals.disclf.pp_txt

For 'preprocess_ops.tokenize', it's just because you don't register config.pp_modules. 
> for pp_mod in config.pp_modules:  importlib.import_module(f'big_vision.pp.{pp_mod}')

You can restart the session and run again.

Remember to modify **'label': label** to **'texts': label** as the inkey in config.evals.disclf.pp_txt is 'texts'.
