### ISSUE TITLE
TPU utilization could be improved further?

### ISSUE THREAD

**Issue by sayakpaul** [google-research/big_vision#3]
Training details are in https://github.com/google-research/big_vision/issues/2

I think the TPU utilization is a bit lower than expected:

![Screenshot 2022-05-11 at 7 42 31 PM](https://user-images.githubusercontent.com/22957388/167870884-086bd964-bb0b-4a95-a1df-ba8df2d437d1.png)

Is this expected? 

I understand there might be other network access factors that can contribute to this but wanted to know.

**Comment by akolesnikoff** [comment]
TPU utilization should be close to 100%. I think your dashboard is showing something else.

My _guess_ it shows percentage of time when TPUs do FLOP-heavy operation, like matrix multiplications. The rest is various data reshapes, weight synchronization and so on. IIUC it is hard to do substantially better than what we have now.

**Comment by sayakpaul** [comment]
Here's what I am doing.

* Go to https://console.cloud.google.com/compute/tpus/detail.
* Then on the monitoring panel, I am getting:

![image](https://user-images.githubusercontent.com/22957388/167969624-9cf7f28c-7ae0-4004-839f-7459758a02dd.png)

I'm probably wrong in selecting that. But you've suggested clues which are enough for now.
