### ISSUE TITLE
Optax update breaks due to jax.Array migration

### ISSUE THREAD

**Issue by colbybanbury** [google-research/big_vision#35]
A recent change in Optax is breaking due to [jax.Array Migration](https://jax.readthedocs.io/en/latest/jax_array_migration.html)

[Optax commit](https://github.com/deepmind/optax/commit/84c644939d0ffe161403607a40996093e0b6c214)

Error:
```
File "bv_venv/lib/python3.8/site-packages/optax/_src/clipping.py" in <module>
    ) -> Tuple[chex.Array, jax.Array]:

AttributeError: module 'jax' has no attribute 'Array'

```

I believe the fix would either be to pin optax to a release. e.g.
`git+https://github.com/deepmind/optax.git@v0.1.4` [here](https://github.com/google-research/big_vision/blob/main/big_vision/requirements.txt#L6)

or increase the minimum Jax version e.g.
`pip install "jax[tpu]>=0.4.1"` [here](https://github.com/google-research/big_vision/blob/main/big_vision/run_tpu.sh#L26)

**Comment by colbybanbury** [comment]
I did some basic tests with the v0.1.4 optax release and confirmed it works, but someone with more vision on the whole repo would know the preferred fix.

**Comment by lucasb-eyer** [comment]
Very late answer, but we'll push some larger updates to the codebase within the next 1-2 months, that will also fix this.

**Comment by akolesnikoff** [comment]
Should be fixed at head now.
