### ISSUE TITLE
Question: Will SigLIP / SigLiT be added to this codebase?

### ISSUE THREAD

**Issue by linzhiqiu** [google-research/big_vision#38]
I mean both model checkpoints and training/inference code

**Comment by lucasb-eyer** [comment]
Hi, yes, we are working on the code release (though there's a chance we'll only finish it slightly after ICCV). Meanwhile, we just released some SigLIP models and colab in #47 and @rwightman has (independently) reimplemented SigLIP in PyTorch OpenCLIP here: https://github.com/mlfoundations/open_clip/pull/634

**Comment by inkzk** [comment]
> Hi, yes, we are working on the code release (though there's a chance we'll only finish it slightly after ICCV). Meanwhile, we just released some SigLIP models and colab in #47 and @rwightman has (independently) reimplemented SigLIP in PyTorch OpenCLIP here: [mlfoundations/open_clip#634](https://github.com/mlfoundations/open_clip/pull/634)

@lucasb-eyer hey there, offerring some pressure hhha. Whether the code will be released soon since ICCV ended for two weeks already

**Comment by lucasb-eyer** [comment]
Since you're pressuring me: The comment that you quoted contains the PR, which was created and merged **three** weeks ago, i.e. before ICCV started. I just forgot to close this issue I guess. Closing :)

(Or is there something else you need?)

**Comment by lucasb-eyer** [comment]
Oops, I was too bold, that was only the colabs (i.e. inference code). The training code was added in #51 which has also been there for three weeks (i.e. before ICCV) but only merged last week.

**Comment by inkzk** [comment]
@lucasb-eyer My bad, great appreciating!~
