### ISSUE TITLE
About RL fine-tuning code release

### ISSUE THREAD

**Issue by byminji** [google-research/big_vision#40]
Hi!

First of all, thanks for sharing those amazing and helpful codebases. I wonder if there is a plan to release the full code of the ICML'23 paper "Tuning computer vision models with task rewards", including the instructions to reproduce the results in the paper.

Thank you :)

**Comment by andsteing** [comment]
@andresusanopinto

**Comment by andresusanopinto** [comment]
Hi @byminji , thanks for your interest. However at the moment we do not have concrete plans to release the full code.
