### ISSUE TITLE
requirements issue

### ISSUE THREAD

**Issue by sneccc** [google-research/big_vision#49]
hi iam doing the pip install -r requirements.txt, but it keeps downloading new dev versions for tfds_nightly
![image](https://github.com/google-research/big_vision/assets/61990796/92dfc7c2-389c-4fa0-9fc9-7dc19a4e5d7e)

**Comment by lucasb-eyer** [comment]
Does this also happen when you manually `pip install tfds_nightly`? If yes, please open an issue with [tensorflow_datasets](https://github.com/tensorflow/datasets). Meanwhile, you can try using just tfds (not nightly), I think most of our code should still.

Closing the issue, as it seems not related to big_vision but instead to tfds, but feel free to re-open if you have evidence of the contrary.
