### ISSUE TITLE
Accuracy of vit-b-16 training

### ISSUE THREAD

**Issue by lucasliunju** [google-research/big_vision#7]
Hi, May I ask the top-1 accuracy of vit-b-16 training on imagenet-1k based on the config file "vit_1ik.py". I find the related paper report the accuracy is about 74.6.

Thank you very much!

Best
Lucas

**Comment by akolesnikoff** [comment]
`vit_i1k` config with the default settings of training the B/16 model is expected to achieve around 79% top-1 accuracy. This setting, as well as other slightly better settings, are described in this paper: https://arxiv.org/abs/2106.10270.
