### ISSUE TITLE
[BUG] in big_vision.models.proj.flexi.vit

### ISSUE THREAD

**Issue by KennyFu1997** [google-research/big_vision#76]
Hello, `big_vision` team!
Thanks for your work on the repository. I found two small typo in the flexivit code:

line 194
restored_params = utils.load_params(None, init_file)
==>
restored_params = utils.load_params(init_file)

line 205
restored_params["embedding"]["kernel"] = resample_patchemb(old=old_patchemb, new_hw=model_cfg.patch_size)
==>
restored_params["embedding"]["kernel"] = resample_patchemb(old=old_patchemb, new_hw=model_cfg.get("patch_size"))

**Comment by akolesnikoff** [comment]
Hi!

Thanks for flagging!

Flexivit project is currently not in sync with the head. Consider fixing bugs in your local fork for now and/or syncing back to the original commit that introduced Flexvit. I hope we find the capacity to update it in the near future, but can not promise.
