### ISSUE TITLE
Reproduced result for flexivit

### ISSUE THREAD

**Issue by liguopeng0923** [google-research/big_vision#77]
Hi,

I want to know how to reproduce the results of your teaser in [Flexivit](https://arxiv.org/pdf/2212.08013.pdf).
<img width="494" alt="image" src="https://github.com/bwconrad/flexivit/assets/61257834/fd4336e2-f25b-4104-bb87-9367066283f7">

An image is split into 2*2, and the accuracy is 84.4%.

Best,
Guopeng.

**Comment by akolesnikoff** [comment]
The teaser pic is just an illustration of the overall idea, showing how to train a single model with different patch sizes.

I believe the actual patch sizes are 24 and 4 respectively, which corresponds to many more tokens.

**Comment by liguopeng0923** [comment]
Fine, thanks. 

Can you provide the trained models with normalization like ImageNet? mean = [0.485, 0.456, 0.406] and std = [0.229, 0.224, 0.225]

This is very important for our later work.
